# Use postgres/example user/password credentials
version: '3.1'

services:
  cykt-db:
    image: postgres:13.3-alpine
    container_name: cykt-db
    environment:
      POSTGRES_PASSWORD: cykt
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/cykt-start.sql:/docker-entrypoint-initdb.d/init.sql
