server:
  port: '${PORT:8080}'
spring:
  flyway:
    enabled: true
  datasource:
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:cykt}
    url: jdbc:postgresql://${POSTGRESQL_DATABASE_URL:10.93.224.3:5432/cykt}

    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:10000}
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:5}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:2}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:30000}
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
